#!/bin/bash
#PBS -V 
#PBS -M yangericlisd@gmail.com
#PBS -m a
#PBS -A ren-group

# properties = {"type": "single", "rule": "bam2bedpe", "local": false, "input": ["sample1/sample1.filtered_dedup.nsrt.bam"], "output": ["sample1/sample1.bedpe.gz"], "wildcards": {"sample": "sample1"}, "params": {"jobname": "sample1.bam2bedpe"}, "log": ["log/sample1.bam2bedpe.log"], "threads": 1, "resources": {}, "jobid": 5, "cluster": {"time": "walltime=12:00:00", "ppn": "nodes=1:ppn=1", "queue": "home"}}
module load samtools
. ~/.bashrc
. ~/.condainit
#conda activate /home/yangli1/anaconda3/envs/r_env/
 cd /projects/ps-renlab/yangli/scripts/snATACutils/00.data_processing && \
/home/yangli1/anaconda3/envs/snakemake/bin/python3.8 \
-m snakemake sample1/sample1.bedpe.gz --snakefile /projects/ps-renlab/yangli/scripts/snATACutils/00.data_processing/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /projects/ps-renlab/yangli/scripts/snATACutils/00.data_processing/.snakemake/tmp.gopgu3dd sample1/sample1.filtered_dedup.nsrt.bam --latency-wait 5 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://github.com/snakemake/snakemake-wrappers/raw/ \
  -p --allowed-rules bam2bedpe --nocolor --notemp --no-hooks --nolock \
--mode 2  && touch /projects/ps-renlab/yangli/scripts/snATACutils/00.data_processing/.snakemake/tmp.gopgu3dd/5.jobfinished || (touch /projects/ps-renlab/yangli/scripts/snATACutils/00.data_processing/.snakemake/tmp.gopgu3dd/5.jobfailed; exit 1)

