#!/bin/bash
#PBS -V 
#PBS -M yangericlisd@gmail.com
#PBS -m a
#PBS -A ren-group

# properties = {"type": "single", "rule": "tsse2depth", "local": false, "input": ["sample1/sample1.bam"], "output": ["sample1/sample1.tsse2depth.ok", "sample1/sample1.filtered_dedup.nsrt.bam"], "wildcards": {"sample": "sample1"}, "params": {"calTSSePE": "../bin/calTSSePE", "outdir": "sample1/tsseANDdepth", "bam": "sample1/tsseANDdepth/filtered_dedup.bam", "anno_gtf": "/projects/ps-renlab/yangli/genome/mm10/gencode.vM16.annotation.gtf", "jobname": "sample1.tsse"}, "log": ["log/sample1.tsse2depth.log"], "threads": 1, "resources": {}, "jobid": 3, "cluster": {"time": "walltime=12:00:00", "ppn": "nodes=1:ppn=1", "queue": "home"}}
module load samtools
. ~/.bashrc
. ~/.condainit
#conda activate /home/yangli1/anaconda3/envs/r_env/
 cd /projects/ps-renlab/yangli/scripts/snATACutils/00.data_processing && \
/home/yangli1/anaconda3/envs/snakemake/bin/python3.8 \
-m snakemake sample1/sample1.tsse2depth.ok --snakefile /projects/ps-renlab/yangli/scripts/snATACutils/00.data_processing/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /projects/ps-renlab/yangli/scripts/snATACutils/00.data_processing/.snakemake/tmp.gopgu3dd sample1/sample1.bam --latency-wait 5 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://github.com/snakemake/snakemake-wrappers/raw/ \
  -p --allowed-rules tsse2depth --nocolor --notemp --no-hooks --nolock \
--mode 2  && touch /projects/ps-renlab/yangli/scripts/snATACutils/00.data_processing/.snakemake/tmp.gopgu3dd/3.jobfinished || (touch /projects/ps-renlab/yangli/scripts/snATACutils/00.data_processing/.snakemake/tmp.gopgu3dd/3.jobfailed; exit 1)

